### ISSUE TITLE
Thread support in Linux script

### ISSUE THREAD

**Issue by ninaandrup** [ninaandrup/ZKBoo#10]
I could not get this to work myself. My computer would not run with more than 1 thread...

**Comment by ninaandrup** [comment]
@jaschdoc whenever you have time, you can take a look at this. The script I'm refering to: https://github.com/ninaandrup/ZKBoo/blob/main/MPC_SHA256/benchmark.sh

**Comment by jaschdoc** [comment]
I think the variable should be all uppercase i.e., `THREADS` but I'm not sure.
